In [ ]:
from cluster_sim.app,utils import get_node_coords
import numpy as np

nums = [48, 51, 3, 0, 12, 60, 63, 42, 38, 22, 26, 37, 41, 21, 25, 15]

print([get_node_coords(i, (4, 4, 4)) for i in nums])

[[0, 0, 3], [3, 0, 3], [3, 0, 0], [0, 0, 0], [0, 3, 0], [0, 3, 3], [3, 3, 3], [2, 2, 2], [2, 1, 2], [2, 1, 1], [2, 2, 1], [1, 1, 2], [1, 2, 2], [1, 1, 1], [1, 2, 1], [3, 3, 0]]


In [45]:
def myrule(x, y, z):
    # return x % 3 == 0 and y % 3 == 0 and z % 3 == 0
    if x % 3 != 0 and y % 3 != 0 and z % 3 != 0:
        return True
    return False

nums_that_match_myrule = []
for i in range(4*4*4):
    if myrule(*get_node_coords(i, (4, 4, 4))):
        nums_that_match_myrule.append(f"{i}, Z;")
        print(f"{get_node_coords(i, (4, 4, 4))} Z;")
        

print(nums_that_match_myrule)
print(sorted(nums))

print(set(nums) - set(nums_that_match_myrule))

[1, 1, 1] Z;
[2, 1, 1] Z;
[1, 2, 1] Z;
[2, 2, 1] Z;
[1, 1, 2] Z;
[2, 1, 2] Z;
[1, 2, 2] Z;
[2, 2, 2] Z;
['21, Z;', '22, Z;', '25, Z;', '26, Z;', '37, Z;', '38, Z;', '41, Z;', '42, Z;']
[0, 3, 12, 15, 21, 22, 25, 26, 37, 38, 41, 42, 48, 51, 60, 63]
{0, 3, 37, 38, 41, 42, 12, 15, 48, 51, 21, 22, 25, 26, 60, 63}


In [ ]:
print("\n".join(nums_that_match_myrule),strip())

0, Z;
3, Z;
12, Z;
15, Z;
48, Z;
51, Z;
60, Z;
63, Z;


In [26]:
import numpy as np
from cluster_sim.app.utils import get_node_coords

x = np.array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
 0, 0, 0])

max_inds = np.argwhere(x == np.max(x))

for i in max_inds:
    print(i)
    print(get_node_coords(i, (5, 5, 5)))


[6]
(array([1]), array([1]), array([0]))
[10]
(array([0]), array([2]), array([0]))
[11]
(array([1]), array([2]), array([0]))
[13]
(array([3]), array([2]), array([0]))
[14]
(array([4]), array([2]), array([0]))
[19]
(array([4]), array([3]), array([0]))
[20]
(array([0]), array([4]), array([0]))
[22]
(array([2]), array([4]), array([0]))
[23]
(array([3]), array([4]), array([0]))


In [20]:
max_inds

(array([ 6, 10, 11, 13, 14, 19, 20, 22, 23]),)

In [ ]:
shape = (4, 4, 4)

scale_factor = 2






In [34]:
import itertools

In [55]:
def generate_unit_cell_coords(shape, scale_factor):
    """
    Find the bottom left corner of each unit cell in a 3D grid.
    """

    # Calculate the number of cubes in each dimension
    num_cubes = np.array(shape) // (scale_factor + 1)
    
    unit_cell_locations = []
    for i in itertools.product(range(num_cubes[0]), range(num_cubes[1]), range(num_cubes[2])):
        unit_cell_locations.append(np.array(i) * (scale_factor + 1))

    return unit_cell_locations



In [56]:
generate_unit_cell_coords((7, 7, 7), 2)

[array([0, 0, 0]),
 array([0, 0, 3]),
 array([0, 3, 0]),
 array([0, 3, 3]),
 array([3, 0, 0]),
 array([3, 0, 3]),
 array([3, 3, 0]),
 array([3, 3, 3])]